FROM ghcr.io/open-webui/open-webui:main

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends nodejs npm \
    && npm cache clean --force \
    && rm -rf /var/lib/apt/lists/*
